CREATE TABLE Sensor
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL UNIQUE
);

CREATE TABLE Measurement
(
    id                int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id         int REFERENCES Sensor (id) ON DELETE CASCADE,
    temperature_value float8    NOT NULL,
    raining           boolean   NOT NULL,
    created_at        timestamp NOT NULL
);
